name: Build SqlSugar

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    # FIX: Point to the 'Src' directory where the .sln file actually resides
    - name: Restore dependencies
      run: dotnet restore Src/SqlSugar.sln

    # FIX: Point to the 'Src' directory here as well
    - name: Build
      run: dotnet build Src/SqlSugar.sln --no-restore --configuration Release

    - name: Embold Analyse
      shell: bash
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL}} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        
        # Using the ID you provided: 1233cdd1464463dcd122b3c07a9856a1
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS}}/api/v1/repositories/1233cdd1464463dcd122b3c07a9856a1/scans/config/download" --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" -o repository-configuration.json
        echo "Download repository configuration file done"
        
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u ${{ vars.EMBOLD_URL_CS}} -t ${{ secrets.EMBOLD_TOKEN_CS}} -r 1233cdd1464463dcd122b3c07a9856a1 -b . -d ./embold-data -c ./repository-configuration.json -v
